function changeColour() {
  // An array containing the valid hexadecimal characters
  var hexNumbers = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
  ];

  // A variable to store the generated hex code
  var hexCode = "";

  // Generate a random 6-digit hex code
  for (var i = 0; i < 6; i++) {
    // Generate a random index within the range of the hexNumbers array
    var randomIndex = Math.floor(Math.random() * hexNumbers.length);

    // Append the character at the random index to the hexCode string
    hexCode += hexNumbers[randomIndex];
  }

  // Update the HTML content of the element with id "hexCode" to display the generated hex code
  document.getElementById("hexCode").innerHTML = hexCode;

  // Set the background color of the body element to the generated hex code
  document.getElementsByTagName("body")[0].style.backgroundColor =
    "#" + hexCode;
}

// Explanation:

// 1. The changeColour() function is defined to generate a random hex color code and update the page accordingly.

// 2. An array named hexNumbers is created, which contains the valid hexadecimal characters (0-9 and A-F).

// 3. A variable named hexCode is declared and initialized as an empty string. This variable will store the generated hex code.

// 4. A for loop is used to generate a random 6-digit hex code. The loop runs 6 times since a hex color code consists of 6 digits.

// 5. Inside the loop, a random index is generated using Math.random() and Math.floor(). The random index is calculated by multiplying a random decimal number between 0 and 1 (generated by Math.random()) with the length of the hexNumbers array and then rounding it down to the nearest whole number.

// 6. The character at the random index in the hexNumbers array is appended to the hexCode string.

// 7. After the loop completes, the generated hex code is displayed on the page by updating the HTML content of the element with the id "hexCode" using document.getElementById("hexCode").innerHTML.

// 8. The background color of the body element is set to the generated hex code by accessing the first element in the array-like collection returned by document.getElementsByTagName("body") and using the style.backgroundColor property to assign the color value.

// Summary: This changeColour() function generates a random hex color code, updates the displayed code on the page, and changes the background color of the body element to the generated color.

// ---------------------------------------------------------->

function copyHexCode() {
  var copyText = document.getElementById("hexCode").textContent;

  // Create a temporary textarea element
  var tempTextArea = document.createElement("textarea");
  tempTextArea.value = copyText;
  document.body.appendChild(tempTextArea);

  // Select the text within the textarea
  tempTextArea.select();
  tempTextArea.setSelectionRange(0, 99999); // For mobile devices

  // Copy the selected text to the clipboard
  document.execCommand("copy");

  // Remove the temporary textarea element
  document.body.removeChild(tempTextArea);

  // Show an alert message
  alert("Copied to clipboard: " + "#" + copyText);
}

// Explanation:

// 1. The copyHexCode() function is defined to copy the hex code displayed on the page to the clipboard.

// 2. The copyText variable is assigned the content of the element with the id "hexCode". The textContent property retrieves the text content of an element.

// 3. A temporary textarea element, tempTextArea, is created using the createElement() method. This element will be used to store the hex code text temporarily.

// 4. The value property of tempTextArea is set to the hex code text, allowing it to be selected and copied.

// 5. The tempTextArea element is appended to the document body using appendChild() to make it accessible.

// 6. The select() method is called on tempTextArea to select the text within it.

// 7. The setSelectionRange() method is used to set the selection range from index 0 to a large number (99999). This is done to ensure that the text is fully selected, especially on mobile devices.

// 8. The execCommand("copy") is called on the document object to execute the copy command, copying the selected text to the clipboard.

// 9. The tempTextArea element is removed from the document body using removeChild() to clean up after copying the text.

// 10. An alert message is shown to indicate that the hex code has been copied to the clipboard.

// Summary: This code allows users to click the "Copy Hex Code" button, which triggers the copyHexCode() function. It retrieves the hex code from the page, creates a temporary textarea element, copies the text to the clipboard, removes the temporary element, and displays an alert message confirming the successful copy

// ---------------------------------------------------------->
